# Generated by Django 2.2.6 on 2019-10-05 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cypher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('dice_type', models.CharField(choices=[('d1', 'd4'), ('d1', 'd6'), ('d1', 'd8'), ('d1', 'd10'), ('d1', 'd12'), ('d1', 'd20'), ('d%', 'Percentile')], max_length=2)),
                ('dice_qty', models.IntegerField()),
                ('mod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeckCypher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cypher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyphers.Cypher')),
                ('deck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyphers.Deck')),
            ],
        ),
    ]
