# Generated by Django 2.2.6 on 2019-10-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cypher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('dice_type', models.CharField(choices=[('d1', 'd4'), ('d1', 'd6'), ('d1', 'd8'), ('d1', 'd10'), ('d1', 'd12')], max_length=2)),
                ('dice_qty', models.IntegerField()),
                ('mod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cyphers', models.ManyToManyField(related_name='Decks', to='cyphers.Cypher')),
            ],
        ),
    ]
