# Generated by Django 2.2.6 on 2019-10-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='cyphers',
            field=models.ManyToManyField(related_name='Cyphers', to='cyphers.Cypher'),
        ),
    ]
