# Generated by Django 2.2.6 on 2019-10-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphers', '0002_auto_20191009_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='cyphers',
            field=models.ManyToManyField(related_name='Decks', to='cyphers.Cypher'),
        ),
    ]
