# Generated by Django 2.2.6 on 2019-10-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphers', '0003_auto_20191009_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='cyphers',
            field=models.ManyToManyField(related_name='decks', to='cyphers.Cypher'),
        ),
    ]
