# Generated by Django 2.2.6 on 2019-10-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphers', '0004_auto_20191009_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='cyphers',
            field=models.ManyToManyField(related_name='Decks', to='cyphers.Cypher'),
        ),
    ]
