# Generated by Django 2.2.6 on 2019-10-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphers', '0005_auto_20191010_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='cyphers',
            field=models.ManyToManyField(related_name='decks', to='cyphers.Cypher'),
        ),
    ]
